version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: p1@ntoys
      MYSQL_DATABASE: ecom_stock
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: p1@ntoys
    ports:
      - 8000:80
    depends_on:
      - db
volumes:
  db_data:
    driver: local
    